apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llmcomp-ingress
  namespace: llmcomp
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
     - llmcomp.local
    secretName: llmcomp-tls-cert # Le certificat sera stock√© ici
  rules:
  - host: llmcomp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: llmcomp-service
            port:
              number: 80
