apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmcomp-deployment
  namespace: llmcomp
  labels:
    app: llmcomp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llmcomp
  template:
    metadata:
      labels:
        app: llmcomp
    spec:
      # Sécurité au niveau du Pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: llmcomp
        image: scorpprocs/llmcomp:latest
        ports:
        - containerPort: 8080 # Changé en 8080 pour le mode non-root
        
        # Sécurité au niveau du Container
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true # Optionnel: empêche d'écrire dans le système de fichiers du container

        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
